name: Pixel
version: 0.3
author: Groot_23
main: me.groot_23.pixel.PixelPlugin
depend: [NBTAPI]
api-version: 1.14

commands:
  pjoin:
    usage: /<command> <game> <map>
  toggle_spectator:
    usage: /<command>
  pdata:
    usage: /<command> <player> <data id> [list | get | set] <key> <value>
  pkit_unlock:
    usage: /<command> <player> <group> <kit> [get | set] <true | false>
  psign:
    usage: /<command> <sign_type> <game> <map>
  